# Generated by Django 4.2.5 on 2023-09-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
