# Generated by Django 4.2.5 on 2023-09-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coupon_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
