# Generated by Django 4.2.5 on 2023-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vacancy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount_of_use',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
