# Generated by Django 4.2.5 on 2023-09-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_coupon_is_used_coupon_amount_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dateOfActual',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='dateOfActual',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
