# Generated by Django 4.2.5 on 2023-09-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_news_dateofactual_review_dateofactual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['dateOfActual'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='employee',
            name='foto',
            field=models.ImageField(default='app/Images/default.jpg', upload_to='app/Images'),
        ),
    ]
